Runtime Error:
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Desktop\CodeBase\compiler\example.py", line 3, in <module>
    print(a[i])
          ~^^^
IndexError: list index out of range